export const HARDWARE_ICONS: Record<string, string> = {
  'play': '▶',
  'pause': '❚❚',
  'play-pause': '▶/❚❚',
  'stop': '■',
  'record': '●',
  'fast-forward': '▶▶',
  'rewind': '◀◀',
  'skip-forward': '▶▶|',
  'skip-backward': '|◀◀',
  'arrow-up': '▲',
  'arrow-down': '▼',
  'arrow-left': '◀',
  'arrow-right': '▶',
  'triangle-up': '△',
  'triangle-down': '▽',
  'triangle-left': '◁',
  'triangle-right': '▷',
  'plus': '+',
  'minus': '−',
  'eject': '⏏',
  'search-skip': '⏭',
  'loop-redo': '↺',
  'sync-lock': '⟳',
  'settings-gear': '⚙',
};
