/**
 * PR-J: regenerate `src/data/tutorials/<deviceId>/*.ts` from the
 * canvas's working snapshot `.pipeline/<id>/agents/tutorial-review/
 * tutorials.json`. Called from `doTutorialPR` BEFORE git push so any
 * PR-I 🛠 Fix → Apply patches actually make it into the opened PR.
 *
 * Approach (per user-confirmed Option A): pure JSON-stringify template
 * inside a typed TS wrapper. No AST. No round-trip parse. The .ts
 * files become genuinely derived artifacts — hand-edits between
 * pipeline runs are unsupported and will be silently overwritten.
 *
 * The deviceRegistry.ts is NOT auto-mutated. When a new device first
 * lands a tutorial PR, the human reviewer adds the import + entry
 * during code review of the opened PR.
 */
import fs from 'fs';
import path from 'path';

interface MinimalTutorial {
  id: string;
  deviceId?: string;
  [key: string]: unknown;
}

export interface RegenerateResult {
  ok: boolean;
  error?: string;
  outDir?: string;
  filesWritten?: string[];
  tutorialCount?: number;
}

/** kebab-case → camelCase. `split-keyboard-zones` → `splitKeyboardZones`. */
export function kebabToCamel(id: string): string {
  return id.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

/** deviceId → registry array variable name. `cdj-3000` → `cdj3000Tutorials`. */
export function deviceIdToArrayName(deviceId: string): string {
  const camel = deviceId.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
  return `${camel}Tutorials`;
}

/** One tutorial → one .ts file body. */
export function tutorialToTs(t: MinimalTutorial): string {
  const ident = kebabToCamel(t.id);
  const json = JSON.stringify(t, null, 2);
  return `// AUTO-GENERATED by scripts/pipeline-runner.ts (tutorial-pr phase).
// Source: .pipeline/${t.deviceId ?? ''}/agents/tutorial-review/tutorials.json
// Do NOT hand-edit — edits between pipeline runs are silently overwritten.
import { Tutorial } from '@/types/tutorial';

export const ${ident}: Tutorial = ${json};
`;
}

/**
 * Build the index.ts content for one device. Mirrors the shape of
 * existing hand-authored indexes (per-tutorial import + named array
 * + named re-export block) so the rest of the codebase requires no
 * changes.
 */
export function indexToTs(deviceId: string, tutorials: MinimalTutorial[]): string {
  const arrayName = deviceIdToArrayName(deviceId);
  const idents = tutorials.map((t) => kebabToCamel(t.id));
  const imports = tutorials
    .map((t) => `import { ${kebabToCamel(t.id)} } from './${t.id}';`)
    .join('\n');
  const arrayEntries = idents.map((i) => `  ${i},`).join('\n');
  const reExports = idents.map((i) => `  ${i},`).join('\n');
  return `// AUTO-GENERATED by scripts/pipeline-runner.ts (tutorial-pr phase).
// Do NOT hand-edit — regenerated from canvas state on every approve.
${imports}
import { Tutorial } from '@/types/tutorial';

export const ${arrayName}: Tutorial[] = [
${arrayEntries}
];

export {
${reExports}
};
`;
}

/**
 * Regenerate ALL tutorial .ts files + the index.ts for one device.
 * Idempotent: writing the same canvas state produces byte-identical
 * output (modulo timestamps that aren't included in the template).
 *
 * `outDir` is `<repoRoot>/src/data/tutorials/<deviceId>` — created
 * if it doesn't exist. Stale .ts files NOT in the new tutorials list
 * are deleted, so removing a tutorial via Layer-5 / PR-K flow
 * doesn't leave orphan files.
 */
export function regenerateTutorialFiles(
  deviceId: string,
  tutorials: MinimalTutorial[],
  outDir: string,
): RegenerateResult {
  try {
    fs.mkdirSync(outDir, { recursive: true });

    const filesToKeep = new Set<string>([
      'index.ts',
      ...tutorials.map((t) => `${t.id}.ts`),
    ]);

    // Remove stale files (tutorials that existed before but are no
    // longer in canvas state). Skip non-.ts files to be safe.
    for (const existing of fs.readdirSync(outDir)) {
      if (!existing.endsWith('.ts')) continue;
      if (!filesToKeep.has(existing)) {
        fs.unlinkSync(path.join(outDir, existing));
      }
    }

    const written: string[] = [];
    for (const t of tutorials) {
      const filename = `${t.id}.ts`;
      fs.writeFileSync(path.join(outDir, filename), tutorialToTs(t));
      written.push(filename);
    }

    fs.writeFileSync(path.join(outDir, 'index.ts'), indexToTs(deviceId, tutorials));
    written.push('index.ts');

    return {
      ok: true,
      outDir,
      filesWritten: written,
      tutorialCount: tutorials.length,
    };
  } catch (err) {
    return {
      ok: false,
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

/**
 * Convenience wrapper used by the pipeline runner. Reads
 * tutorials.json from the canvas's working dir and regenerates
 * straight into the worktree's src/data/tutorials/<id>/.
 */
export function regenerateTutorialsFromCanvas(opts: {
  deviceId: string;
  repoRoot: string;
}): RegenerateResult {
  const { deviceId, repoRoot } = opts;
  const tutorialsJsonPath = path.join(
    repoRoot,
    '.pipeline',
    deviceId,
    'agents',
    'tutorial-review',
    'tutorials.json',
  );
  if (!fs.existsSync(tutorialsJsonPath)) {
    return { ok: false, error: `tutorials.json not found at ${tutorialsJsonPath}` };
  }
  let tutorials: MinimalTutorial[];
  try {
    tutorials = JSON.parse(fs.readFileSync(tutorialsJsonPath, 'utf-8'));
  } catch (err) {
    return {
      ok: false,
      error: `failed to parse tutorials.json: ${err instanceof Error ? err.message : String(err)}`,
    };
  }
  if (!Array.isArray(tutorials)) {
    return { ok: false, error: 'tutorials.json must be a top-level array' };
  }
  const outDir = path.join(repoRoot, 'src', 'data', 'tutorials', deviceId);
  return regenerateTutorialFiles(deviceId, tutorials, outDir);
}
